### ISSUE TITLE
OutOfMemoryException when converting converting docx with many images

### ISSUE THREAD

**Issue by serbadea** [mwilliamson/dotnet-mammoth#1]
I get an OutOfMemoryException when doing a conversion of a document (rather small - 1 MB), but with a lot of images. Here is the stack trace:

```
   at System.Text.StringBuilder.ToString()
   at Mammoth.Couscous.java.lang.StringBuilder.toString()
   at Mammoth.Couscous.org.zwobble.mammoth.internal.html.Html.write(List`1 nodes)
   at Mammoth.Couscous.org.zwobble.mammoth.internal.InternalDocumentConverter__Anonymous_9.apply(List`1 arg0)
   at Mammoth.Couscous.org.zwobble.mammoth.internal.results.InternalResult`1.map[R](Function`2 function)
   at Mammoth.Couscous.org.zwobble.mammoth.internal.InternalDocumentConverter.convertToHtml(Optional`1 path, Archive zipFile)
   at Mammoth.Couscous.org.zwobble.mammoth.internal.InternalDocumentConverter__Anonymous_0.apply(Archive zipFile)
   at Mammoth.Couscous.org.zwobble.mammoth.internal.InternalDocumentConverter.withDocxFile[T](InputStream stream, Function`2 function)
   at Mammoth.Couscous.org.zwobble.mammoth.internal.InternalDocumentConverter__Anonymous_1.get()
   at Mammoth.Couscous.org.zwobble.mammoth.internal.util.PassThroughException.unwrap[T](SupplierWithException`2 supplier)
   at Mammoth.Couscous.org.zwobble.mammoth.internal.InternalDocumentConverter.convertToHtml(InputStream stream)
   at Mammoth.DocumentConverter.ConvertToHtml(Stream stream)
```

I'm attaching 2 files, one with 950 pages (that works) and one with 1000 pages (that fails). The IIS worker process goes up to 10 GB of memory or more processing those two. For the first document (950 images) works, for the second it crashes. The resulting HTML output for the first document is about 1 GB in size, if that counts...
Thank you for your support!

[Big document 1000 pages.docx](https://github.com/mwilliamson/dotnet-mammoth/files/988912/Big.document.1000.pages.docx)
[Big document 950 pages.docx](https://github.com/mwilliamson/dotnet-mammoth/files/988913/Big.document.950.pages.docx)

**Comment by mwilliamson** [comment]
The latest version of Mammoth supports custom image handlers, so you could see if the images are the problem by creating an image handler that does nothing i.e. something like

```csharp
var converter = new DocumentConverter()
    .ImageConverter(image => new Dictionary<string, string>());
```

If that stops the memory issue, then you could change the images to be stored in separate files rather than inline.

**Comment by serbadea** [comment]
Indeed, the images were the problem. So I will now save the files to disk, instead of having them embedded into HTML.
Thank you for your quick answer and for the handler!
